
# Configure a default setup of Home Assistant (frontend, api, etc)
default_config:

# Text to speech
tts:
  - platform: google_translate


# Database setup
recorder:
  db_url: !secret recorder_db_url
  purge_keep_days: 60

automation: !include automations.yaml
script: !include scripts.yaml
scene: !include scenes.yaml
